### ISSUE TITLE
_usr_bin_mate-settings-daemon.1000.crash

### ISSUE THREAD

**Issue by realimsirius** [linuxmint/mintsystem#105]
Linux Mint 19.1 MATE. System is up to date.

===================================================================
 GDB Log                                                           
===================================================================

warning: core file may not match specified executable file.
[New LWP 1540]
[New LWP 1541]
[New LWP 1542]
[New LWP 1543]
[New LWP 1686]
[New LWP 1736]
[New LWP 1551]
[New LWP 1737]
[New LWP 1738]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/mate-settings-daemon'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f1ce507da80 (LWP 1540))]

===================================================================
 GDB Backtrace                                                     
===================================================================

warning: core file may not match specified executable file.
[New LWP 1540]
[New LWP 1541]
[New LWP 1542]
[New LWP 1543]
[New LWP 1686]
[New LWP 1736]
[New LWP 1551]
[New LWP 1737]
[New LWP 1738]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/mate-settings-daemon'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f1ce507da80 (LWP 1540))]
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f1ce2bee801 in __GI_abort () at abort.c:79
#2  0x00007f1ce3231335 in g_assertion_message () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f1ce323139a in g_assertion_message_expr () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f1cbffffa21 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse-mainloop-glib.so.0
#5  0x00007f1ccbb734e5 in pa_pstream_unlink () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so
#6  0x00007f1ccbdbe095 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#7  0x00007f1ccbdbe8a0 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#8  0x00007f1ccbdc01e5 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#9  0x00007f1ccbdc16da in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#10 0x00007f1ccbb6dc61 in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so
#11 0x00007f1cbffffec8 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse-mainloop-glib.so.0
#12 0x00007f1ce320a417 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007f1ce320a650 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007f1ce320a962 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007f1ce3effa25 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x0000558be84befff in main ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================

warning: core file may not match specified executable file.
[New LWP 1540]
[New LWP 1541]
[New LWP 1542]
[New LWP 1543]
[New LWP 1686]
[New LWP 1736]
[New LWP 1551]
[New LWP 1737]
[New LWP 1738]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/mate-settings-daemon'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f1ce507da80 (LWP 1540))]

Thread 9 (Thread 0x7f1cb86d2700 (LWP 1738)):
#0  0x00007f1ce2cc2bf9 in __GI___poll (fds=0x7f1cb86d1ad0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f1cbf9237c4 in snd_mixer_wait () from /usr/lib/x86_64-linux-gnu/libasound.so.2
No symbol table info available.
#2  0x00007f1cbfbecfca in ?? () from /usr/lib/x86_64-linux-gnu/libmatemixer/libmatemixer-alsa.so
No symbol table info available.
#3  0x00007f1ce3232195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f1ce2fa66db in start_thread (arg=0x7f1cb86d2700) at pthread_create.c:463
        pd = 0x7f1cb86d2700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139761329972992, -1026562045266917821, 139761329970304, 0, 139761792610000, 140720485833744, 1151122257049257539, 1151002543060649539}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#5  0x00007f1ce2ccf88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 8 (Thread 0x7f1cb96d4700 (LWP 1737)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007f1ce325077f in g_cond_wait () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f1cbfbed00d in ?? () from /usr/lib/x86_64-linux-gnu/libmatemixer/libmatemixer-alsa.so
No symbol table info available.
#3  0x00007f1ce3232195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f1ce2fa66db in start_thread (arg=0x7f1cb96d4700) at pthread_create.c:463
        pd = 0x7f1cb96d4700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139761346758400, -1026562045266917821, 139761346755712, 0, 94059419329696, 140720485833744, 1151120059099743811, 1151002543060649539}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#5  0x00007f1ce2ccf88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 7 (Thread 0x7f1cca4c8700 (LWP 1551)):
#0  0x00007f1ce2cc2bf9 in __GI___poll (fds=0x558bea1bc0b0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f1ce320a5c9 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f1ce320a6dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f1ce112a82d in ?? () from /usr/lib/x86_64-linux-gnu/libdconf.so.1
No symbol table info available.
#4  0x00007f1ce3232195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f1ce2fa66db in start_thread (arg=0x7f1cca4c8700) at pthread_create.c:463
        pd = 0x7f1cca4c8700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139761629824768, -1026562045266917821, 139761629822080, 0, 94059416719520, 140720485836944, 1151091757412746819, 1151002543060649539}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f1ce2ccf88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 6 (Thread 0x7f1cb9ed5700 (LWP 1736)):
#0  0x00007f1ce2cc2bf9 in __GI___poll (fds=0x7f1c94001b30, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f1ccbde2481 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#2  0x00007f1ccbdd3e40 in pa_mainloop_poll () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#3  0x00007f1ccbdd44d0 in pa_mainloop_iterate () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#4  0x00007f1ccbdd4560 in pa_mainloop_run () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#5  0x00007f1ccbde23c9 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#6  0x00007f1ccbb84318 in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so
No symbol table info available.
#7  0x00007f1ce2fa66db in start_thread (arg=0x7f1cb9ed5700) at pthread_create.c:463
        pd = 0x7f1cb9ed5700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139761355151104, -1026562045266917821, 139761355148416, 0, 94059419056976, 140720485824944, 1151118961198728771, 1151002543060649539}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#8  0x00007f1ce2ccf88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 5 (Thread 0x7f1cb6ecf700 (LWP 1686)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007f1ce325089a in g_cond_wait_until () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f1ce31dd571 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f1ce31ddb2c in g_async_queue_timeout_pop () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f1ce3232c3e in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f1ce3232195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#6  0x00007f1ce2fa66db in start_thread (arg=0x7f1cb6ecf700) at pthread_create.c:463
        pd = 0x7f1cb6ecf700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139761304794880, -1026562045266917821, 139761304792192, 0, 94059417270592, 140720485836944, 1151099183948072515, 1151002543060649539}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#7  0x00007f1ce2ccf88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 4 (Thread 0x7f1cd9033700 (LWP 1543)):
#0  0x00007f1ce2cc2bf9 in __GI___poll (fds=0x7f1cd401d590, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f1ce320a5c9 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f1ce320a962 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f1ce37f80e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007f1ce3232195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f1ce2fa66db in start_thread (arg=0x7f1cd9033700) at pthread_create.c:463
        pd = 0x7f1cd9033700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139761876678400, -1026562045266917821, 139761876675712, 0, 94059415743264, 139761893460096, 1151049330115184195, 1151002543060649539}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f1ce2ccf88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 3 (Thread 0x7f1cd9834700 (LWP 1542)):
#0  0x00007f1ce2cc2bf9 in __GI___poll (fds=0x7f1cd4007ce0, nfds=2, timeout=2662) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f1ce320a5c9 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f1ce320a6dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f1ce320a721 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f1ce3232195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f1ce2fa66db in start_thread (arg=0x7f1cd9834700) at pthread_create.c:463
        pd = 0x7f1cd9834700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139761885071104, -1026562045266917821, 139761885068416, 0, 94059415743104, 139761893459712, 1151048230066685507, 1151002543060649539}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f1ce2ccf88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7f1cda035700 (LWP 1541)):
#0  0x00007f1ce2cc2bf9 in __GI___poll (fds=0x558bea109de0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f1ce320a5c9 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f1ce320a6dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f1cda03d36d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#4  0x00007f1ce3232195 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f1ce2fa66db in start_thread (arg=0x7f1cda035700) at pthread_create.c:463
        pd = 0x7f1cda035700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139761893463808, -1026562045266917821, 139761893461120, 0, 94059415740736, 140720485836416, 1151055928258692675, 1151002543060649539}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f1ce2ccf88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7f1ce507da80 (LWP 1540)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0, 94059417815425, 94059417815444, 94059417815344, 94059417815444, 0, 2064, 124, 139761457038641, 140720485836896, 139762043821120, 139762040317912, 566935683072, 2048, 343597383680, 7}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007f1ce2bee801 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xfefefeff, sa_sigaction = 0xfefefeff}, sa_mask = {__val = {94059417816592, 0, 140720485836896, 140720308486145, 8863086342219767808, 72057594037927936, 16777216, 5548434740920451072, 139759930310656, 94059417816592, 0, 0, 8863086342219767808, 139761457038641, 94059417816592, 78}}, sa_flags = -481477152, sa_restorer = 0x7ffc0a922860}
        sigs = {__val = {32, 0 <repeats 15 times>}}
        __cnt = <optimized out>
        __set = <optimized out>
        __cnt = <optimized out>
        __set = <optimized out>
#2  0x00007f1ce3231335 in g_assertion_message () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f1ce323139a in g_assertion_message_expr () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f1cbffffa21 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse-mainloop-glib.so.0
No symbol table info available.
#5  0x00007f1ccbb734e5 in pa_pstream_unlink () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so
No symbol table info available.
#6  0x00007f1ccbdbe095 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#7  0x00007f1ccbdbe8a0 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#8  0x00007f1ccbdc01e5 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#9  0x00007f1ccbdc16da in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
No symbol table info available.
#10 0x00007f1ccbb6dc61 in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so
No symbol table info available.
#11 0x00007f1cbffffec8 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse-mainloop-glib.so.0
No symbol table info available.
#12 0x00007f1ce320a417 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#13 0x00007f1ce320a650 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#14 0x00007f1ce320a962 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#15 0x00007f1ce3effa25 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#16 0x0000558be84befff in main ()
No symbol table info available.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f1ce2bee801 in __GI_abort () at abort.c:79
#2  0x00007f1ce3231335 in g_assertion_message () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f1ce323139a in g_assertion_message_expr () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f1cbffffa21 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse-mainloop-glib.so.0
#5  0x00007f1ccbb734e5 in pa_pstream_unlink () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so
#6  0x00007f1ccbdbe095 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#7  0x00007f1ccbdbe8a0 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#8  0x00007f1ccbdc01e5 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#9  0x00007f1ccbdc16da in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#10 0x00007f1ccbb6dc61 in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so
#11 0x00007f1cbffffec8 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse-mainloop-glib.so.0
#12 0x00007f1ce320a417 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007f1ce320a650 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007f1ce320a962 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007f1ce3effa25 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x0000558be84befff in main ()

**Comment by realimsirius** [comment]
Error disappeared after recent update.
